[build]
  command = "npm run build"
  publish = ".next"
  functions = "functions"

[[plugins]]
package = "@netlify/plugin-nextjs"

[dev]
  command = "npm run dev"

[[redirects]]
from = "/*"
to = "https://archive.mieuxvoter.fr/:splat"
status = 200
force = false
